// Merchant Terms and Conditions payload for Pay10 Bahrain
const merchantTcsData = [
  {
    tabName: "Merchant T&Cs",
    content: `
<h3><strong>Merchant Terms and Conditions</strong></h3>
<p>These Terms and Conditions are part of a legally binding agreement between the Merchants ("you", "your") and PayTen B.S.C Closed ("we", "us", "our", Pay10). These Terms and Conditions govern your receipt and use of the Pay10 Services.</p>

<h6><strong>1. Definitions</strong></h6>
<ul>
<li><strong>"Account"</strong> means an account portal established for You by Pay10 and accessed by You (or by Pay10 on Your behalf) through an API or integration or online portal to utilize the Pay10 Services.</li>
<li><strong>"Acquiring Bank"</strong> or <strong>"Acquirer"</strong> means the financial institution supplying You with the ability to accept credit and debit cards for payments. The financial institution will charge You fees for providing these services.</li>
<li><strong>"BHD"</strong> means the official currency of the Kingdom of Bahrain being the Bahraini Dinars.</li>
<li><strong>"API"</strong> means an application programming interface.</li>
<li><strong>"Authorization"</strong> means the process by the Acquiring Bank, the Issuer, and/or the relevant Card Scheme (including domestic schemes such as Benefit) electronically or otherwise convey the approval of the Customer's payment with respect to a Transaction on the Merchant's platform through Pay10's payment processing system.</li>
<li><strong>"Beneficial Owner"</strong> means any person who either directly or indirectly owns or controls at least 20% or more of Your ownership interests as well as a person who exercises substantial control over You. There must be at least one Beneficial Owner identified.</li>
<li><strong>"Benefit"</strong> means the national payment network in the Kingdom of Bahrain.</li>
<li><strong>"Card Association"</strong> means any card scheme, payment network or association involved in processing Payment Cards of a specific brand, including any domestic card scheme in the Kingdom of Bahrain and international schemes such as American Express Company, Discover Financial Services, JCB Co., Ltd., Mastercard Incorporated, Visa Inc., or any debit network, together with each of their subsidiaries and successors, or any other Card Association supported by Pay10 from time to time.</li>
<li><strong>"Chargeback"</strong> means a request from a customer for an approved and settled Transaction amount to be reversed to such Customer.</li>
<li><strong>"Customer"</strong> means any person who is procuring a product and/or service from the Merchant and chooses to pay using the Pay10 Services.</li>
<li><strong>"Data"</strong> means (a) information relating to the Merchant and its business provided to Pay10 or collected by Pay10 in connection with this Agreement, including without limitation the Merchant's legal name, trading name, addresses, contact details, business activity, licence numbers, settlement instructions, configuration settings, and transaction metadata ("Merchant Data"); and (b) personal data (as defined in Law No. (30) of 2018 with respect to Personal Data Protection of the Kingdom of Bahrain ("Bahrain PDPL")) relating to the Merchant's customers which is provided to or collected by Pay10 in connection with the Pay10 Services, including names, CPR or national ID or passport details, contact details, IBANs, card details, and transaction details ("Customer Personal Data").</li>
<li><strong>"Day"</strong> means calendar day.</li>
<li><strong>"Pay10 Device"</strong> means any payment acceptance machine provided or enabled by Pay10 for use by the Merchant.</li>
<li><strong>"Merchant Enrollment Form"</strong> means the electronic or digital form completed and submitted by the Merchant in connection with its use of the Pay10 Services, which sets out the specific commercial terms agreed between the Parties. The Merchant Enrollment Form shall form an integral part of, and be incorporated by reference into, this Terms and Conditions. In the event of any conflict or inconsistency between the provisions of the Merchant Enrollment Form and these Terms and Conditions, the Merchant Enrollment Form shall prevail solely with respect to the commercial terms expressly set out therein, and these Terms and Conditions shall prevail in all other respects.</li>
<li><strong>"Fee(s)"</strong> means the fee charged by Pay10 to the Merchant for each transaction processed through the Pay10 App, as set out in the Merchant Enrollment Form. Such fees may be reviewed and mutually agreed upon annually and/or adjusted in the event of any increase in acquiring and/or regulatory costs.</li>
<li><strong>"Intellectual Property"</strong> has the meaning in the Applicable Laws.</li>
<li><strong>"Issuing Bank"</strong> or <strong>"Issuer"</strong> means the Customer's Bank.</li>
<li><strong>"Merchant(s)"</strong> means any corporate entity that will receive and use Pay10 Services.</li>
<li><strong>"Merchant Account"</strong> means the account created by the Merchant on the Pay10 App to register as a merchant, subject to Know Your Customer (KYC) requirements, anti-money laundering (AML) compliance, and Pay10's due diligence and background checks.</li>
<li><strong>"Party"</strong> or <strong>"Parties"</strong> reference to Party means either Pay10 or You as the context indicates, and Parties means both Pay10 and You collectively.</li>
<li><strong>"PCI DSS"</strong> means Payment Card Industry Data Security Standard issued by the Payment Card Industry Security Standards Council.</li>
<li><strong>"Privacy Policy"</strong> means the Pay10 Privacy Policy available either on the Pay10 Biz App, Pay10's website or otherwise provided to the Merchant, and which may be modified by Pay10 in its sole discretion from time to time.</li>
<li><strong>"Pay10 Application/Pay10 App"</strong> for the purposes of this Agreement, means the Pay10 Biz App made available by Pay10 that enables Merchants and Customers to access the Pay10 Services for the purpose of seeking, receiving and using payment processing products and services, as may be updated or modified by Pay10 at its discretion from time to time.</li>
<li><strong>"Pay10 Services"</strong> means the payment processing products and services that Pay10 is authorized to provide via Pay10 App, either directly or indirectly through Third-Party Service Providers, pursuant to the license granted by the Central Bank of Bahrain, as identified and selected by the Merchant in their respective Enrollment Form.</li>
<li><strong>"Refund"</strong> means a reversal of a Transaction voluntarily initiated by the Merchant in accordance with this Agreement, whereby funds for a previously authorized and settled Transaction are returned to the Customer, excluding any reversal initiated by the Customer or the Issuing Bank through a Chargeback process.</li>
<li><strong>"Reversal Transaction"</strong> means a transaction that has been successfully initiated but subsequently reversed prior to settlement, either due to cancellation, error, or system decline, and which does not constitute a Refund or a Chargeback.</li>
<li><strong>"Rules"</strong> means the rules, requirements, policies, procedures, and standards issued by the Central Bank of Bahrain, Card Associations or other industry bodies such as the PCI Security Standards Council, including without limitation the PCI DSS and the PCI Software Security Framework, or any successor or replacement framework or standard implemented by the PCI Security Standards Council, as each may be amended from time to time by the Card Associations or other applicable authorities.</li>
<li><strong>"Settlement"</strong> means the amount that will be paid by Pay10 to the Merchant which is formulated as follows: (a) the aggregate Transaction amounts of all unsettled Transactions successfully Authorized up to the point of Settlement; less (b) the aggregate amount of all transactions reversed prior to settlement (excluding Refund, Chargebacks, Pay10 service charges and VAT); less (c) any Chargebacks of Transactions (unless already deducted from the Settlement Amount earlier); less (d) any overpayment made by Pay10; less (e) any other sums due from or payable by the Merchant under this Agreement.</li>
<li><strong>"Third-Party"</strong> means any party besides You and Pay10.</li>
<li><strong>"Third-Party Service Provider"</strong> means a Third-Party entity that maintains aspects of the Pay10 Services or provides certain bank and/or merchant payment services including but not limited to billing, reporting, Customer service, authorization, and settlement services.</li>
<li><strong>"Trademark(s)"</strong> means any word, name, symbol, logo, device, design, slogan, trade dress, or other indicia of origin, whether registered or unregistered, owned, used, or applied for by Pay10 (including without limitation "Pay10" and "Pay10 Biz App") in connection with its business, products, or services, and any registrations, applications, renewals, or extensions thereof under Applicable Laws.</li>
<li><strong>"Transaction(s)"</strong> means any billable occurrence completed or submitted under Your Account including but not limited to sale, void, refund, credit, offline force, capture, authorization, validate, update or settlement regardless of whether approved or declined.</li>
<li><strong>"Applicable Laws"</strong> means all laws, regulations, rules, directives and requirements of the Kingdom of Bahrain, including without limitation those issued or enforced by the Central Bank of Bahrain pursuant to the Central Bank of Bahrain and Financial Institutions Law 2006 ("CBB Law") and the applicable CBB Rulebook.</li>
</ul>

<h6><strong>2. Term</strong></h6>
<p>2.1 The term of this Agreement shall commence once Pay10 accepts your Merchant Enrollment Form upon successfully completing a compliance check and verification on You and shall remain in full force and effect until terminated pursuant to Section 14 (Termination) ("Term").</p>

<h6><strong>3. Merchant Information</strong></h6>
<p>3.1 You represent and warrant that (i) all information and documentation You have provided, and will provide, to Pay10 is true and correct in all respects and up to date, and that You understand and agree that any incorrect and/or false information may have adverse action including rendering this Agreement as null and void and/or termination of this Agreement; (ii) You will promptly update Pay10 in writing with any changes to information and documentation You have previously supplied. Pay10 fully reserves its right to, temporarily or permanently, reject, refuse, block, and/or suspend Your access to the Pay10 Services and/or to terminate this Agreement, with or without notice to You, if Pay10 reasonably believes, at its sole and absolute discretion, that You have supplied any information which is misleading, untrue, inaccurate, fraudulent, or incomplete, or Pay10 forms the view, at its sole and absolute discretion, that continuing to do business with You is not in the interests of Pay10; and (iii) You shall at all times use the Pay10 Services for lawful purposes and in full compliance with applicable laws and regulations of the Kingdom of Bahrain.</p>

<h6><strong>4. Use of Pay10 Services</strong></h6>
<h6><strong>4.1 Pay10 services Grant to you</strong></h6>
<ul>
<li>(a) You are granted a limited, revocable, non-transferable, non-sublicensable, and non-exclusive right to use the Pay10 Services during the Term so long as You are in compliance with (i) all of the terms and conditions of this Agreement, including being current in paying all applicable fees to Pay10 as referenced in the Merchant Enrollment Form; and (ii) the current policies, procedures, guidelines and restrictions contained in this Agreement and policies, procedures, guidelines and restrictions communicated to You by Pay10, all of which may be amended by Pay10 from time to time. Pay10 shall, directly or through its Third-Party Service Providers, provide the Pay10 Services to You in accordance with this Agreement and the rights granted to You under this Agreement are for the purposes contained in this Agreement and for no other purpose.</li>
<li>(b) Your use of the Pay10 Services shall be restricted to You, only. You shall not submit Data to Pay10 or otherwise request, initiate, introduce, or process Transactions using the Pay10 Services on behalf of any other entity or individual not cited as the Merchant in the Merchant Application Form attached to this Agreement. Any attempt by You to use the Pay10 Services on behalf of another entity or individual in breach of this Agreement may result in, inter alia, Your obligation to pay to Pay10 additional fees and charges and/or Pay10 may revoke Your right to access or use the Pay10 Services and/or Pay10 may terminate this Agreement without any prior notice to You and/or Pay10 may claim from You any losses or damages arising from such conduct.</li>
<li>(c) In addition to Your compliance with this Agreement, You will comply, at Your own expense, with all Rules, and applicable laws, regulations, rules, ordinances and orders of governmental authorities. You shall not use the Pay10 Services in any prohibited manner, including, but not limited to, those set forth in Annexure 'A' and/or set forth in the Rules and/or in furtherance of any activity that may cause Pay10 or any Third-Party to be subject to, including but not limited to, liability, loss, negative reputational harm, investigation, prosecution, or legal action.</li>
<li>(d) You acknowledge that Pay10 has a legal requirement to carry out money laundering checks, credit searches, know your customer (KYC) and know your business (KYB), and other fraud-prevention enquiries in respect of You. You shall provide full co-operation to Pay10 in fulfilling this requirement including providing complete and accurate information together with supporting KYC/KYB documentation for Pay10's own validation, prior to onboarding, on a periodic basis and upon the occurrence of any trigger event. Any record of these searches and enquiries may be used by Pay10 to make credit, compliance and insurance decisions about You or to prevent fraud and money laundering. Pay10 may provide records of these searches and enquiries to any fraud prevention agencies or competent authorities should You give Pay10 false or inaccurate information or Pay10 suspects fraud. Should Pay10 suspect fraud or You do not satisfy Pay10's background verification or if You are identified as a sanctioned or high-risk party, Pay10 may provide a record of these searches and enquiries to any regulatory authority or to any competent authorities or agencies.</li>
</ul>
<h6><strong>4.2 Data License Grant by You to Pay10</strong></h6>
<p>4.2.1 You grant Pay10 a royalty-free, non-exclusive, and sublicensable licence to use Data (as defined in this Agreement) solely as necessary for Pay10 to provide the Pay10 Services to You and to perform Pay10's obligations under this Agreement. Pay10 may collect and hold Data from and about You and Your Customers: (a) for the purpose of providing You with the Pay10 Services (including onboarding, transaction processing, settlement, fraud prevention, and compliance with regulatory requirements); and/or (b) to consider and review Your eligibility and ongoing risk profile for the Pay10 Services.</p>
<p>4.2.2 You acknowledge and agree that Pay10 may share Data with its affiliates, Third-Party Service Providers, payment schemes (including Benefit), banks, fraud prevention agencies, government authorities or regulators, and courts, strictly to the extent required for the purposes set out above or as required by Applicable Law. Pay10 shall process Customer Personal Data in accordance with its Privacy Policy and Applicable Laws (including PDPL) and shall implement appropriate technical and organisational measures to protect such Data.</p>
<p>4.2.3 You warrant and represent that You have obtained, and will maintain, all required consents, notices and lawful bases to permit Pay10 and its Third-Party Service Providers to process Customer Personal Data in accordance with this Agreement. You shall indemnify Pay10 only to the extent a claim arises directly from Your failure to obtain such consents, notices or lawful bases, or from inaccurate or misleading Data provided by You. This indemnity shall not apply to the extent the claim results from Pay10's breach of its obligations under this Agreement or its non-compliance with Applicable Law.</p>
<h6><strong>4.3 Support of Pay10 services</strong></h6>
<p>4.3.1 Regardless of whether Pay10 Services are provided by Pay10 directly or through a Third-Party Service Provider, You and Pay10 agree that Pay10 (and not the Third-Party Service Provider) will provide all required support obligations in relation to the Pay10 Services. You acknowledge and agree that all such support obligations shall rest solely with Pay10, including in respect of any Pay10 Services provided by a Third-Party Service Provider, or any additional supplier, agent, vendor, contractor or Third-Party providing any part of the Pay10 Services.</p>

<h6><strong>5. Roles and Responsibilities of the Merchant</strong></h6>
<p>The Merchant shall:</p>
<p>5.1 Use the Pay10 Services in accordance with the Agreement and pay the Fees as provided in the Merchant Enrollment Form.</p>
<p>5.2 Be responsible for understanding and complying with this Agreement, and any and all applicable laws, bylaws, rules, regulations, operating regulations, policies, procedures, guidelines and manuals applicable for the Services (as may be amended, updated or replaced from time to time).</p>
<p>5.3 Be responsible for technical integration and shall ensure that:</p>
<ul>
<li>5.3.1 Your e-Channels are enabled for connection to Pay10 service offering.</li>
<li>5.3.2 and/or where applicable, Your other operating systems are enabled for connection with Pay10 Devices for any and all authentication, acceptance and processing procedures approved by Pay10 used to complete Transactions.</li>
</ul>
<p>5.4 Comply with all reasonable technical, security and privacy directions, standards and specifications by Pay10.</p>
<p>5.5 Where applicable, be responsible for the safekeeping, usage, and proper maintenance of the Pay10 Devices and must not tamper with or allow unauthorized access or usage, and comply with the terms and conditions relating to the Pay10 Devices, and the deployment and operation of the Pay10 Devices.</p>
<p>5.6 Comply with the Service Levels and Critical Incident Management provided in Annexure B.</p>
<p>5.7 Provide Pay10 with full and accurate information and documents as required by Pay10, to enable Pay10 to satisfy its onboarding and ongoing compliance requirements. Failure to provide all necessary information and KYC documents shall constitute a material breach of the Agreement, and You shall be liable to indemnify Pay10 in the event of any remediation required or in case of regulator censure or penalties. Without prejudice to any other rights Pay10 may have, Pay10 has the right to terminate this Agreement with immediate effect.</p>
<p>5.8 Use best efforts to market and promote the Company's services including dynamic QR codes generated through the Pay10 application or, where applicable, through the Pay10 Device, which shall be supplied by the Company on loan to the Merchant.</p>
<p>5.9 If applicable, utilize the Pay10 Device where appropriate to process payments by its customer. The Pay10 Device shall at all times remain the property of Pay10, and Pay10 reserves the right in future to charge the Merchant a monthly device fee after consultation and alignment with the Merchant as per market practice.</p>
<p>5.10 Adhere to the Company's guidelines and policies regarding marketing as may be issued and updated from time to time.</p>
<p>5.11 Ensure that it conducts itself in a professional, ethical and transparent manner at all times in relation to this Agreement.</p>
<p>5.12 The Company may, from time to time, supply the Merchant with promotional materials intended to enhance visibility of Pay10 and encourage Customer transactions. Such materials may include, without limitation, tent cards, tabletop displays, acrylic or plastic standees, window decals, door stickers, POS terminal stickers, skins, or any other branding or marketing items ("Promotional Materials"). The Merchant agrees to prominently display such Promotional Materials at its premises, including counters, doors, windows, or near POS terminals, as and when reasonably requested by the Company. The Merchant shall not alter, remove, or obscure the Promotional Materials without the prior written consent of the Company and shall ensure they are kept in a clean and presentable condition at all times.</p>
<p>5.13 To complete Pay10's onboarding process, including the Merchant Application Form, and pass Pay10's prevailing "know your customer" checks and other checks and processes in place, and must be approved by Pay10. If onboarding is successfully completed, Pay10 shall notify Merchant. Based on Pay10 classification, the onboarding process will be as follows:</p>
<ul>
<li>i. In case of Enterprise: Merchant to email Enterprise KYC documents in line with applicable regulatory requirements to the Pay10 operations account manager assigned to the Enterprise's account.</li>
<li>ii. In case of SME and Micro: at the initial stage, SME and Micro Merchants will be onboarded manually through the Relationship Manager, who will collect the SME/Micro KYC documents and submit them to Pay10. Once the Pay10 Biz App/web onboarding journey is launched, such Merchants may be onboarded via the Pay10 Biz App or web link by uploading the SME/Micro KYC documents onto the App/web link.</li>
</ul>
<p>5.14 Taxes: The Merchant is responsible for all applicable taxes arising from the fees received under this Agreement.</p>

<h6><strong>6. Data (Security, Collection, Transfer and Retention) and Credentials</strong></h6>
<h6><strong>6.1 Use and Sharing of Your Data</strong></h6>
<ul>
<li>(a) Pay10 will collect, retain, use, store, transmit, process and share information and Data collected from You and Your Customers, and Pay10 will share such information and Data with its Third-Party Service Providers, in accordance with Pay10's Privacy Policy. You consent to the collection, use, retention, storage, transmission, processing and transfer of Data, and the sharing of Data with Third-Party Service Providers and other Third-Party vendors, agents, and suppliers, as described in this section and pursuant to Pay10's Privacy Policy. You agree to monitor Pay10's Privacy Policy periodically to review any possible amendments. By using the Pay10 Services after modifications to Pay10's Privacy Policy, you have agreed to such amendments.</li>
<li>(b) Pay10 may collect, use, share, and hold personal or non-public information about You and Your Customers, including but not limited to: Your name, address, telephone number, email address, ID number and/or tax identification number and payment data, Transaction data, including account numbers and purchase history, as well as Your Customers' names, mailing &amp; shipping addresses, email addresses, phone number, types of purchases and descriptions of purchases, and various Transaction data related to Your Customers ("Data") for the purpose of considering eligibility for the Pay10 Services and for the purpose of providing You and Your Customers with the Pay10 Services. Pay10 shall have the right to (i) use the Data as necessary to perform the Pay10 Services (including distributing the Data to its Third-Party Service Providers and other Third-Parties, as requested by You and as necessary to perform the Pay10 Service); (ii) maintain the Data as long as necessary or as required by law and used internally for record keeping, internal reporting, and support purposes; (iii) compile and disclose Data in the aggregate where the Data is not identifiable, including without limitation, calculating merchant averages by region or industry; (iv) provide the Data as required by Rules, law or court order, or to defend Pay10's rights in a legal dispute; (v) comply with any privacy code, policy or terms which have been adopted by or are binding on the parties; and (vi) restrict access to any Data only to persons who need to access the Data for the purpose of performing obligations under this Agreement.</li>
<li>(c) Pay10 warrants and undertakes that it shall process Your Data and Your Customers' Data in accordance with the applicable data protection laws and handle such Data with care and in a confidential manner in accordance with the relevant applicable data protection laws.</li>
<li>(d) Pay10, its subsidiaries, Third-Party Service Providers, suppliers and/or their agents and/or contractors may have access to, use, and transfer such Data among themselves as necessary for the purpose of the provision and management of the Pay10 Services. Pay10 may further transfer Data with (a) non-affiliated entities that assist Pay10 in providing products and services that You have requested; (b) companies that provide support services to Pay10; (c) companies that provide marketing services on behalf of Pay10; or (d) as otherwise provided by law.</li>
<li>(e) In evaluating Your eligibility for, provision of, administration and management of the Pay10 Services, as well as under circumstances described in the Privacy Policy that may be changed from time to time, Pay10 may obtain various consumer reports regarding You or Beneficial Owners associated with You from Third-Parties, run a credit check or obtain other personal or credit information about You or Your Beneficial Owner(s). Pursuant to such, Pay10 may, from time to time, obtain consumer-identifying and credit information (including credit reports) and other consumer reports from multiple consumer reporting agencies for any individual required by Pay10 or Beneficial Owner associated with You, for the purpose of verifying the identities of such individuals and evaluating the fraud and credit risk associated with You in connection with a business transaction.</li>
<li>(f) You expressly authorize Pay10 to investigate Your individual and business history and background, consumer-identifying and credit information (and that of any of Your and Your authorized representatives, directors, officers, partners, proprietors, owners, etc.), and to obtain credit or consumer reports or other background investigation reports on each of them that Pay10 considers necessary to both review the acceptance of Your merchant application initially, and thereafter at any time during Your use of the Pay10 Services. You also authorize any person or credit reporting agency that issues consumer reports to answer those credit inquiries and to furnish that information to Pay10.</li>
<li>(g) You represent and warrant to Pay10 that You have obtained, and will provide to Pay10 upon request, written instructions and all authorizations, consents, and disclosures necessary from each such individual for Pay10 to obtain (and for a consumer reporting agency to provide) such information including consumer reports of such individual to Pay10. You represent and warrant that You will ensure that such individual shall also authorize Pay10's sharing of information of such individual in connection with obtaining such consumer reports from the consumer reporting agencies and other Third-Party providers who conduct background and identification screening. You agree to cooperate with and provide Pay10 with any information or documentation needed for Pay10 to obtain such information from consumer reporting agencies and agree that such information and documentation will comply with all applicable requirements under all laws and regulations in Bahrain for the purposes of this Agreement.</li>
<li>(h) While Pay10 uses commercially reasonable efforts to safeguard Data obtained, processed, stored, and transmitted while using Pay10 Services, Pay10 does not warrant that Data will be processed, stored and/or transmitted without unauthorized interception or modification or that Data will not be accessed or compromised by any unauthorized Third-Parties.</li>
<li>(i) In case of Data breaches, Pay10 commits to immediately inform You about such event and disclose all information necessary to deal with its consequences.</li>
<li>(j) You will comply at all times with the terms of this Agreement, all applicable Rules, and all then-current legal obligations and security measures, including without limitation: (a) the laws and regulations of the Kingdom of Bahrain; (b) the rules, directives and regulations issued by the Central Bank of Bahrain (including, where applicable, the Financial Institutions Law 2006); (c) the rules of BenefitPay and any applicable Card Association rules; (d) PCI DSS; and (e) any other requirements of competent authorities having jurisdiction.</li>
</ul>
<h6><strong>6.2 Your Duties Towards Data Security</strong></h6>
<ul>
<li>a) You will comply at all times with the terms of this Agreement, all applicable Rules, and then-current legal obligations and security measures including without limitation those issued by the Central Bank of Bahrain and compliance with the Financial Institutions Law 2006, applicable laws, regulations and ordinances, the rules of Benefit or any other Card Association rules, directives and regulations of the CBB supported by Pay10 from time to time (where applicable), PCI DSS and any other governing body. You will comply with all Pay10 security protocols, notices and safeguards in effect during the Term of this Agreement. Notwithstanding Pay10's assistance in understanding the Rules, You expressly acknowledge and agree that You are assuming the risk of compliance with all provisions of the Rules, regardless of whether You have possession of such Rules. You warrant that You have taken such precautions as are necessary to ensure that Your Data and Your Customer's Data is protected, and that Your electronic and physical systems are secure from breach, intrusion, virus and compromise by any unauthorized Third-Parties. In the event that Your system is breached and an unauthorized Third-Party has access to or has accessed Data, You shall notify the designated parties as required under any applicable laws or industry guidelines and shall immediately notify Pay10 of such breach within 48 to 72 hours and take such prompt action and precautions as necessary to prevent any continuous or additional breach, and to mitigate any further loss and/or damages to You and/or Your Customer(s). You agree and undertake to fully indemnify Pay10 against any and all losses and/or damages arising from Your system being breached and access gained to Data by an unauthorized Third-Party.</li>
<li>b) You are solely responsible for the security of Data residing on servers owned or operated by You, or any Third-Party designated by You (e.g., a web hosting company, processor, or other service provider), including Payment Card numbers and any other Data. You shall comply with all Card Association rules, directives and regulations of the Central Bank of Bahrain, applicable laws and regulations governing the collection, retention, storage, transfer and use by You of Payment Card and other financial information, and You agree to provide notice to Your Customers on Your website that discloses how and why personal and financial information is collected and used, including uses governed by this Agreement.</li>
<li>c) You are solely responsible for verifying the veracity, accuracy and completeness of all Transactions submitted to and processed by Pay10 associated with Your Account, and for verifying that all corresponding funds are accurately processed. If You use any API provided in connection with the Pay10 Services, You are solely responsible for such use of the API, the security of Your credentials associated with the API, and the security of information and data submitted through the API. The fees associated with any and all Transactions and associated Data submitted to Pay10 are earned by Pay10 and shall not be reimbursed. Pay10 and its Third-Party Service Providers will not be liable for any Transactions, including without limitation those that are unauthorized, improperly processed or approved, wrongfully declined, or otherwise, or for any access to any Transaction or Account data or Your or Your Customers' Data, including without limitation any unauthorized, illegal, or fraudulent access. Pay10's liability for unauthorized Transactions or improperly processed Transactions solely attributable to the negligence of Pay10 is limited pursuant to Section 17 (Limitation of Liability).</li>
<li>d) You will not use, disclose, sell or disseminate any card, cardholder, bank account, ACH or Customer Data (including data accessed under or otherwise regulated by the CBB) obtained in connection with a Transaction except for purposes of completing or settling a Transaction and/or resolving chargebacks, retrievals or similar issues involving a Transaction unless required to do so by court order or competent governmental or regulatory authority (including the CBB Laws), or pursuant to a lawful subpoena or order.</li>
<li>e) You are solely responsible for compiling and retaining permanent records of all Data for Your reference. Except as otherwise provided in this Agreement, Pay10 shall have no obligation to store, retain, report or otherwise provide any copies of or access to any records of Transactions or other Data collected or processed by Pay10. Upon termination of this Agreement, Pay10 shall have no obligation to provide You with any Data. You shall use proper controls for and limit access to all Data. Prior to discard, You shall render all Data unreadable and abide by any laws or regulations imposed on You for Data destruction and/or disposal.</li>
<li>f) You represent and warrant that You have provided notice to, and obtained consent from, Your Customer whose Data You supply to Pay10 with regard to: (i) the purposes for which Your Customer's Data has been collected; (ii) the sharing and use of Your Customer's Data with Pay10 and its Third-Party Service Providers and its and their agents, suppliers, and contractors; (iii) which parts of Customer's Data are obligatory and which parts, if any, are voluntary; and (iv) how Your Customers can access and, if necessary, rectify the Data You hold about them. Neither Pay10 nor its Third-Party Service Providers are responsible for any consequences resulting from Your failure to provide notice or obtain consent from such individuals, nor for You providing outdated, incomplete or inaccurate information.</li>
</ul>
<h6><strong>6.3 Your Username and Password Credentials</strong></h6>
<ul>
<li>a) In connection with Your rights described in Section 4.1 (Pay10 Services Grant to You), Pay10 will issue to You, or permit You to use, a username and password to enable You and/or Your employees and agents to access Your Account and use the Pay10 Services. You will restrict access to such username, password, and Account to Your employees and agents as may be reasonably necessary and consistent with the purposes of this Agreement, and You will ensure that each such employee and agent accessing and using the Account is aware of and otherwise complies with all applicable provisions of this Agreement and any recommendations and notices regarding such use and access. You are solely responsible for the actions and/or inactions of each such employee and agent, and You fully indemnify Pay10 for any losses and/or damages arising from their conduct.</li>
<li>b) You are solely responsible for maintaining adequate security and control of any and all usernames, passwords, or any other codes that are issued to You by Pay10 or selected by You, for purposes of giving You access to the Pay10 Services. Pay10 shall be entitled to rely on information it receives from You and may assume that all such information was lawfully transmitted by or on behalf of You with the necessary authorizations from You.</li>
</ul>
<h6><strong>6.4 Audits</strong></h6>
<p>6.4.1 Pay10 and its Third-Party Service Providers, or their designees, may, during the Term of this Agreement and for a period of 12 months thereafter, conduct an audit of Your books, records, and operations to verify the accuracy of fees, Your proper use of the Pay10 Services, and compliance with this Agreement and with applicable laws and Rules. The auditing party will use reasonable efforts to provide at least five Days' advance notice of any such audit and will use reasonable efforts to ensure that the audit does not unreasonably disrupt Your business. You will provide all reasonable cooperation with any such audit and will provide all requested information and records and reasonable access to Your premises, computer systems, databases, equipment, and personnel. Each party will bear its own costs in connection with any such audit, except that if an audit reveals a material breach of this Agreement by You, You will reimburse Pay10 or the Third-Party Service Provider for its costs incurred in connection with such audit, and where applicable, You will be liable for any and all losses and/or damages arising from such material breach. If the audit identifies that You have underpaid any fees due under this Agreement, You will pay all such amounts within seven (7) calendar days.</p>

<h6><strong>7. Rejection</strong></h6>
<p>7.1 Pay10 reserves the right, in its sole and absolute discretion, to, with or without cause, reject and/or refuse to process as part of the Pay10 Services any payment by Your Customer.</p>

<h6><strong>8. Refund</strong></h6>
<ul>
<li>a) Pay10 reserves the right, in its sole and absolute discretion, to refund the full amount of any payment made by Your Customer with respect to any Transaction where, for whatever reason, You are unable to perform/provide the product and/or service (whether in whole or in part) which Your Customer procured from You and paid for using the Pay10 Services.</li>
<li>b) The total amount of the refund is to be recovered by Pay10 from the settlement funds due to You, and should the settlement funds be insufficient to recoup the refund amount, Pay10 may (i) delay processing the refund until sufficient funds become available, always on the understanding that You indemnify Pay10 of all liability and claims made by Your Customer for such refund; and/or (ii) make a claim to You for payment of such refund amount, which amount You undertake to pay to Pay10 within two (2) Days of receiving the claim from Pay10.</li>
<li>c) It is agreed that Pay10 is entitled to the service Fees for every Transaction processed by Pay10, on behalf of Your Customer(s) using the Pay10 Services to pay You, irrespective of any refund as specified herein.</li>
</ul>

<h6><strong>9. Chargeback</strong></h6>
<ul>
<li>a) In the event that a Chargeback request is received from Your Customer, Pay10 shall inform You accordingly and debit the amount disputed from the Settlement funds due to You on the next Settlement cycle.</li>
<li>b) You shall be entitled to respond to Us in respect of the Chargeback request, and You shall be able to furnish documents and information pertaining to the Transaction, within three (3) Days of You receiving from Us the notification about the Chargeback request from Pay10, in order to substantiate: (i) the completion of the relevant Transaction from Your side; and/or (ii) delivery of goods/services procured by the Customer pursuant to the relevant Transaction.</li>
<li>c) You agree and acknowledge that You shall not further dispute the matter and accept that the disputed amount be debited from the Settlement funds due to You in the event that: (i) You are unable to furnish reasonable information as stipulated above; or (ii) Pay10 is not satisfied with the information which You furnished to Us.</li>
<li>d) As Chargebacks may arise a considerable period after the date of the relevant Transaction, the Merchant acknowledges and agrees that, notwithstanding the termination of this Agreement for any reason, Pay10 shall remain entitled to recover Chargebacks and Chargeback Fees and related Fines from the Merchant in respect of all Chargebacks that occur in relation to Transactions effected during the term of this Agreement.</li>
</ul>

<h6><strong>10. Settlement of Transactions</strong></h6>
<ul>
<li>a) The frequency of Settlement of transactions to You depends on the number of transactions processed daily. Pay10 undertakes to use its best efforts to provide a Settlement payment to You as per the frequency indicated and agreed with You. This undertaking is based on all reasonable efforts that Pay10 shall make for matters within its sole control only.</li>
<li>b) To the extent that the Settlement amount for any settlement cycle is negative (i.e. You owe Pay10 a payment), including any amounts recoverable under Clause 8(b), Pay10 shall be entitled to recoup such amount from any future amount that becomes due to You, including from the Settlement funds of subsequent Settlement payments that may be due to You.</li>
</ul>

<h6><strong>11. Fees, Fines and Taxes</strong></h6>
<ul>
<li>a) In consideration of the Pay10 Services, the Merchant agrees to pay Pay10 such Fees as set out in the Merchant Enrollment Form. The applicable Fees shall be deducted by Pay10 from the Merchant's ongoing settlement to their Account in respect of each completed Transaction on the platform.</li>
<li>b) Pay10 reserves the right to increase the Fees at any time with 30 days' prior written notice; such Fee increases shall only become effective for the Services rendered by Pay10 starting at the end of the notice period. The Merchant may, however, during the one-month notice period, terminate this Agreement by providing written notice to Pay10 prior to the end of the one-month notice period.</li>
<li>c) You are solely responsible for, and will indemnify and hold Pay10 and its Third-Party Service Providers harmless from, payment of all applicable VAT, fees and duties (only excluding taxes levied on Pay10 based on its own net income).</li>
<li>d) Pay10 shall be entitled to debit the amount equivalent to any fines, penalties and/or other charges imposed on Pay10 by an Acquirer or any other person resulting from Chargebacks and any other fees or fines imposed with respect to acts or omissions of the Merchant.</li>
<li>e) Notwithstanding anything to the contrary hereunder, the Merchant shall forthwith compensate/reimburse Pay10 for any loss or penalty borne by Pay10 due to any suspected illegal, fraudulent or prohibited activity by the Merchant or the Merchant's Customer.</li>
<li>f) Pay10 is hereby authorised and entitled to debit the disputed amount from any amount due and payable to the Merchant in terms of this Agreement. The Merchant agrees and undertakes to execute all authorizations and documents as may be required in this regard by Pay10 from time to time. Pay10 further reserves the right to debit amounts erroneously paid in excess to the Merchant.</li>
<li>g) All Fees and charges subject to this Agreement are exclusive of VAT and other applicable taxes, which will be separately payable by the Merchant where applicable to invoiced amounts.</li>
<li>h) Pay10 reserves the right to set off any amounts due to the Merchant against any amounts owed or other liabilities of the Merchant, now or at any time hereafter due, owing or incurred by the Merchant to Pay10 under, in connection to, or pursuant to this Agreement.</li>
</ul>

<h6><strong>12. Reserve Fund</strong></h6>
<p>12.1 The Merchant acknowledges Pay10's right, at its sole discretion, to set the Reserve Fund to be applied by Pay10 to account for and cover the potential indebtedness of the Merchant, including but not limited to fees, fines, chargebacks, and regulatory penalties, or other financial risks payable from the Merchant to Pay10, based on Pay10's reasonable assessment of transaction volume, historical performance, potential fine exposure and other potential liabilities. Pay10 has the right to adjust the Reserve Fund level in its discretion from time to time to bring it in line with its then-current estimates. Upon the Merchant's first request, Pay10 will inform the Merchant of the information, estimations, assumptions and calculations used by Pay10 to establish the then-current Reserve Fund level.</p>
<p>12.2 After termination of this Agreement, the Reserve Fund shall be released by Pay10 in monthly steps to the Merchant to account for any financial exposure by Pay10. The Reserve Fund will, as standard, be fully released to the Merchant 12 months after processing of Transactions for the Merchant has stopped, unless specifically identified potential liabilities still exist at that point in time.</p>

<h6><strong>13. Trademarks and Intellectual Property</strong></h6>
<p>13.1 Pay10 grants to You the right to use, reproduce, publish, perform and display the Pay10 trademark and logo strictly in accordance with Pay10's branding guidelines ("Branding Guidelines") as published on Pay10's official website https://pay10.bh/ and as may be updated by Pay10 from time to time. Such usage may only be (i) on Your website in connection with Your offering of Pay10 Services to Your Customers; and (ii) in promotional and marketing materials and electronic and printed advertising, publicity, press releases, newsletters and mailings about or related to any of the Pay10 Services. All proposed marketing or promotional uses of the Pay10 trademark and logo must comply with the Branding Guidelines and should be coordinated with Pay10's marketing team at marketing@pay10.com.</p>
<p>13.2 You grant to Pay10 and its Third-Party Service Provider the right to use, reproduce, publish, perform and display Your trademark and logo as follows: (i) in connection with the development, use, reproduction, modification, adaptation, publication, display and performance of the Pay10 Services offered and/or accessible through Your website; and (ii) in promotional and marketing materials and electronic and printed advertising, publicity, press releases, newsletters and mailings about or related to any of the Pay10 Services.</p>
<p>13.3 As between Pay10 and You, Pay10 (or its Third-Party Service Providers, as applicable) owns and retains all right, title and interest in and to the Pay10 Services, Trademarks, copyrights, technology and any related technology utilized under or in connection with this Agreement, including but not limited to all Intellectual Property rights associated pursuant to this Agreement. No title to or ownership, whether in whole or in part, of any of the foregoing is granted or otherwise transferred to You, Your Customers, or any other entity or person under this Agreement. You shall not reverse engineer, disassemble, decompile or otherwise attempt to discover the source code or trade secrets for any of the Pay10 Services or related technology. You agree to promptly report to Pay10 any unauthorized use or infringement of the Pay10 Services or any Pay10 Intellectual Property which comes to Your attention.</p>

<h6><strong>14. Termination</strong></h6>
<h6><strong>14.1 Termination for Cause</strong></h6>
<p>14.1.1 This Agreement may be terminated by either Party with immediate effect without the need for any notice in the following events:</p>
<p>14.1.2 If any Party violates or does not strictly adhere to any of the terms or conditions of this Agreement and/or any other agreement entered into between the Parties, and such violation is not remedied within seven (7) days of a written notification.</p>
<p>14.1.3 If the Merchant is found through an audit or investigation to be participating in any fraudulent activities, or in violation of the applicable AML and Compliance regulations.</p>
<p>14.1.4 If Pay10 determines, in its sole discretion, that Your business practices are detrimental to the achievement of Pay10's business objectives, or if Pay10's relationship with its Third-Party Service Provider terminates or the Third-Party Service Provider otherwise ceases supplying Pay10 with services necessary for the delivery of the Pay10 Services.</p>
<p>14.1.5 If the other Party is at any time declared insolvent or is made subject to similar proceedings leading to insolvency, receivership or bankruptcy, with the exception of a voluntary liquidation purporting a restructuring or a merger or change of control due to restructuring at conditions accepted beforehand by the other Party.</p>
<p>14.1.6 If material changes occur in the nature or place of business of the other Party in a manner that substantially impairs the referring or receiving of Referred Parties under this Agreement.</p>
<h6><strong>14.2 Termination for Convenience</strong></h6>
<p>This Agreement shall remain valid unless terminated by either Party by giving thirty (30) Days' prior written notice to the other Party.</p>
<h6><strong>14.3 Effect of Termination and Survival</strong></h6>
<p>Upon termination of this Agreement for any reason whatsoever, all rights and interests under this Agreement shall be extinguished and shall be given no further force or effect except that (i) all accrued payment obligations under this Agreement shall survive such expiration or termination; and (ii) the rights and obligations of the parties under Section 19.10 (Survival) shall survive termination.</p>
<p>14.4 If the Merchant is deemed "Inactive", meaning that it processes fewer than five (5) Transactions in any thirty (30) consecutive days, for two (2) consecutive months (or such other threshold as Pay10 may determine and notify the Merchant in writing), Pay10 shall first initiate a review and re-engagement process with the Merchant. If, following such review, the Merchant remains Inactive and no satisfactory resolution is reached, Pay10 may, at its discretion, terminate this Agreement.</p>

<h6><strong>15. Confidentiality and Nondisclosure</strong></h6>
<h6><strong>15.1 Use of Confidential Information</strong></h6>
<ul>
<li>a) All information relating to Pay10 or to the Merchant and designated as being confidential, and all information not expressly designated as confidential but which should reasonably be deemed confidential by reason of its nature or content, is considered "Confidential Information". Each party that receives Confidential Information ("Receiving Party") from the other party ("Disclosing Party") agrees to use reasonable best efforts to protect all Confidential Information provided by or disclosed by the Disclosing Party, and in any event, to take precautions at least as great as those taken to protect its own Confidential Information of a similar nature. The Receiving Party will only use the Confidential Information of the Disclosing Party to perform its obligations under this Agreement. Each party agrees that the terms and conditions of this Agreement will be Confidential Information, provided that each party may disclose the terms and conditions of this Agreement to its immediate legal and financial consultants in the ordinary course of its business.</li>
<li>b) Each party agrees not to divulge any confidential information, trade secrets or know-how or any information derived therefrom to any third person or entity, and shall only disclose Confidential Information to employees, agents, contractors, or required third persons on a "need to know" basis who have executed a nondisclosure agreement with similar terms and obligations as restrictive as those set forth in this Agreement.</li>
</ul>
<h6><strong>15.2 Exclusions</strong></h6>
<p>The foregoing restrictions will not apply to any information that: (a) the Receiving Party can document it had in its possession prior to disclosure by the Disclosing Party; (b) was in or entered the public domain through no fault of the Receiving Party; (c) is disclosed to the Receiving Party by a Third-Party legally entitled to make such disclosure without violation of any obligation of confidentiality; (d) is required to be disclosed by applicable laws or regulations (but in such event, only to the extent required to be disclosed); or (e) is independently developed by the Receiving Party without reference to or use of any Confidential Information of the Disclosing Party.</p>

<h6><strong>16. Representations and Warranties</strong></h6>
<h6><strong>16.1 Your Representations and Warranties</strong></h6>
<ul>
<li>(a) You represent and warrant that (i) You are engaged in a lawful business that includes the sale of products and/or services, and are duly licensed to conduct such business under the laws of all jurisdictions in which You conduct business; (ii) all statements made by You pursuant to this Agreement, or in any other document relating hereto by You or on Your behalf, are true, accurate and complete in all material respects; (iii) all Transactions submitted in connection with the Pay10 Services are for bona fide business operations compliant with applicable Rules, laws, and regulations; (iv) You are not engaged in any illegal or fraudulent business operation or any business operation prohibited by any applicable law, regulation, or Rule, or in any business identified on a prohibited activities list promulgated by any Third-Party Service Provider or the Card Associations; and (v) You have all necessary rights to any data or materials You use or provide to Pay10 in conjunction with the Pay10 Services, and no such data or materials infringe the intellectual property rights of any Third-Party. You authorize Pay10 to investigate and confirm the information submitted by You. For this purpose, Pay10 may utilize credit bureau/reporting agencies and/or its own agents, as described in Section 5.1(b) (Use of Your Data).</li>
<li>(b) You represent and warrant that You will comply with all Rules, applicable laws, regulations, rules, ordinances and orders of governmental authorities having jurisdiction.</li>
<li>(c) You will abide by all terms of the then-current policies, procedures, and guidelines of Pay10 governing the Pay10 Services.</li>
</ul>
<h6><strong>16.2 Pay10 Representations and Warranties</strong></h6>
<p>Pay10 Services are designed for use with certain Third-Party programs, including, without limitation, certain internet browser software programs. You will look solely to the developers and manufacturers of such programs with regard to warranty, maintenance or other support regarding the same. Pay10 makes no warranty, express or implied, with regard to any such Third-Party software. Pay10 does not warrant the services of any Third-Party, including without limitation Third-Party Service Providers, the Card Associations, or any regulatory requirements imposed by the CBB or any other concerned authorities in the Kingdom of Bahrain.</p>
<h6><strong>16.3 Warranty Disclaimer</strong></h6>
<p>Pay10 Services are provided on an "as is" and "as available" basis, without any representations or warranties. Pay10 and its Third-Party Service Providers do not represent or warrant that the Pay10 Services will be available, accessible, uninterrupted, timely, secure, accurate, complete, or entirely error free. You may not rely upon any representation or warranty regarding the Pay10 Services by any Third-Party in contravention of the foregoing statements, including, but not limited to representations by Third-Party Service Providers. Pay10 and its Third-Party Service Providers specifically disclaim all representations, warranties and conditions whether express or implied arising by statute, operation of law, usage of trade, course of dealing, or otherwise, including but not limited to warranties or conditions of merchantability, fitness for a particular purpose, non-infringement, or title with respect to the Pay10 Services, or other services or goods provided under this Agreement. You understand and agree that Pay10 and its Third-Party Service Providers shall bear no risk with respect to Your sale of products or services, including without limitation, any risk associated with credit card fraud, ACH fraud, check fraud or chargebacks.</p>
<h6><strong>16.4 Disputes</strong></h6>
<ul>
<li>(a) Any dispute, disagreement, or complaint arising solely from an alleged failure by Pay10 to meet its obligations under this Agreement or any applicable law, or any associated error in the provision of Pay10 Services ("Service Disputes"), should in the first instance be referred to Pay10's Support Center by contacting merchantsupport@pay10.bh, which will ensure that all Service Disputes are handled and addressed in a fair and timely manner. We aim to communicate with you regarding the Service Dispute within a period of seven (7) Days from the date of receipt, and to respond with a decision within fourteen (14) Days from the date we receive the complaint.</li>
<li>(b) Pay10 will investigate Service Disputes, provided that You provide the required reasonable assistance to Pay10 as and when requested. You undertake, within a maximum period of three (3) business Days of Your receipt of such enquiries and claims, to respond to and resolve with Pay10 any Customer enquiries and claims that Pay10 passes on to You.</li>
<li>(c) If the disputed amount is less than five percent (5%) of the total fees invoiced by Pay10 for the relevant billing statement, the total amount invoiced shall be due and payable on or before the due date listed in the invoice for that relevant billing period. If the amount in dispute is greater than five percent (5%) of the total fees invoiced, the disputed amount only may be withheld for a further period of five (5) Days within which the disputed amount must be resolved; the undisputed amount is to be settled on or before the due date listed in the invoice. All disputes must be made in good faith and in writing within five (5) Days after the billing statement date. Fees billed shall be deemed accepted where written objections are not provided to Pay10 within five (5) Days after the billing statement date.</li>
</ul>

<h6><strong>17. Limitation of Liability</strong></h6>
<h6><strong>17.1 Pay10 Disclaimers</strong></h6>
<p>a) Pay10 and its Third-Party Service Providers expressly disclaim any liability or loss, however occurring, including negligence, which arises from or relates to any unauthorized access to your Account, facilities, or to your Data or programs due to accident, illegal or fraudulent means or devices used by any Third-Party, or other causes beyond Pay10's reasonable control.</p>
<p>b) Pay10 and its Third-Party Service Providers expressly disclaim any liability or loss, however occurring, including negligence, arising from or related to: (i) Your failure to properly activate, integrate or secure Your Account(s); (ii) fraudulent transactions processed through Your Account(s); (iii) disruption of Pay10 Services, systems, servers or website by any means, including without limitation DDoS attacks, software viruses, trojan horses, worms, time bombs, or any other technology; (iv) actions or inactions by any Third-Party, including without limitation a Third-Party Service Provider or acquiring bank; (v) unauthorized access to Your Data or Your Customer's data including but not limited to payment card numbers, other personally identifiable information, transaction data or personal information belonging to Pay10, You, Your Customer, or any Third-Party; or (vi) Your sale of products or services (including without limitation any risk associated with payment card fraud, ACH fraud, check fraud, chargebacks, transaction rating, improperly authorized transactions, legitimate but unauthorized transactions, data transmission errors, or any action or omission by a Third-Party).</p>
<p>c) Pay10 and its Third-Party Service Providers expressly disclaim any liability or loss for the legitimacy of Your transactions, orders forwarded from You, and for any and all claims of loss and/or fraud incurred resulting from conclusions drawn from the Data provided by any Pay10 Services, or any associated system or program, or the limitation of the functioning of any associated services or software, hardware, or equipment, whether owned by Pay10 or offered through a Third-Party Service Provider or other entity.</p>
<h6><strong>17.2 Pay10 Limitation of Liability</strong></h6>
<p>a) Under no circumstances will Pay10 or any of its parents, affiliates or Third-Party providers, or any of its officers, directors, employees or agents, be liable for any indirect, incidental, consequential, special or exemplary damages however or whenever arising, including, without limitation, damages for lost revenue, lost profits, anticipated profits, lost business or injury to business reputation, or cost of procurement of substitute services, under any theory of liability or cause of action whether in tort, including negligence, contract or otherwise, regardless of whether it has been advised of the possibility of such damages. Any fines, fees, penalties, assessments or other amounts imposed by the Card Associations are direct damages and will not be deemed to be special, incidental, consequential, or punitive damages.</p>
<p>b) Pay10's total liability to You, whether arising in tort (including negligence), contract or otherwise, under this Agreement or regarding any Pay10 Services, shall not exceed the aggregate compensation Pay10 received for providing the Pay10 Services to You during the thirty (30) Days preceding the date on which the claim arose, or BHD 1,000.00, whichever is less.</p>
<p>c) You will remain liable for any liabilities and losses and other amounts incurred by Pay10 arising under this Agreement that are attributable in whole or in part to: (i) intentional misrepresentation, fraud, wilful or intentional acts or omissions or negligence by You or Your employees or agents, or the failure of any such persons to comply with this Agreement, Rules, applicable laws, rules or regulations; (ii) Your breach of any provision of this Agreement or other applicable agreement associated with the Pay10 Services; (iii) any information, Data, or Transactions that You know or should have known contain inaccuracies or omissions; (iv) any security breach or unauthorized access to Data or Confidential Information caused by the actions of You or any of Your employees or agents; or (v) any assessments, fines, penalties or other amounts (however labelled) imposed by the Card Associations or any governmental or regulatory body or other Third-Party as a result of any action or inaction by You or any of Your employees or agents. All such obligations and amounts imposed by Third-Parties will be deemed direct, not indirect or consequential, damages, and will be collectible notwithstanding any provision in this Agreement to the contrary.</p>

<h6><strong>18. Indemnification</strong></h6>
<p>You shall defend, indemnify, and hold harmless Pay10 and its Third-Party Service Providers, parents, and/or subsidiaries, and any of their officers, directors, agents and employees, from and against any and all claims, actions, proceedings, and suits and all related liabilities, damages, settlements, penalties, fines, costs or expenses (including reasonable attorneys' fees and other litigation expenses) incurred by Pay10, arising out of or relating to:</p>
<ul>
<li>(i) any breach or alleged breach by You of any representation, warranty, or obligation of You set forth in this Agreement;</li>
<li>(ii) Your violation or non-compliance with any Rules, applicable law, rule, regulation, or order;</li>
<li>(iii) any damage or loss caused by negligence, fraud, dishonesty or wilful misconduct by You or any of Your employees, agents or Customers;</li>
<li>(iv) the reliability, accuracy, or legitimacy of Data or purchase orders submitted by You to Pay10;</li>
<li>(v) Transactions, including unauthorized or fraudulent Transactions, submitted using the Pay10 Services, including Transactions rejected by Pay10 or an issuing bank;</li>
<li>(vi) any alleged infringement of a patent, copyright, trademark or other intellectual property right by You, or arising from any data or other materials or technology supplied by You or from Your use of the Pay10 Services in an unauthorized manner;</li>
<li>(vii) any claims by Your Customers, including, without limitation, claims relating to the disclosure of personal data or other consumer data, or claims relating to the goods or services sold by You;</li>
<li>(viii) any alleged or actual violation or non-compliance by You of any Rules, applicable laws, regulations or rules of (a) the Card Associations, including non-compliance with PCI-DSS; or (b) any regulatory body or agency having jurisdiction over the subject matter hereof;</li>
<li>(ix) any violation of Pay10's policies or guidelines; or</li>
<li>(x) any data breach or any unauthorized access, use, or disclosure of Confidential Information, personal data, card information, or Your credentials from systems and networks controlled by You or Your service providers. In the event You cause fines and/or penalties to be charged to Pay10 by the Card Associations or any other entity, You agree to immediately reimburse Pay10 for such fines and penalties.</li>
</ul>

<h6><strong>19. General Provisions</strong></h6>
<h6><strong>19.1 Non-exclusivity</strong></h6>
<p>Each Party acknowledges and agrees that the rights granted to the other Party in this Agreement are non-exclusive, and that, without limiting the generality of the foregoing, nothing in this Agreement shall be deemed or construed to prohibit either Party from participating in similar business arrangements as those described in this Agreement.</p>
<h6><strong>19.2 Notices</strong></h6>
<p>All notices to You shall be given electronically, sent to the electronic email address provided by or for You during registration for the Pay10 Services and/or posted in the Merchant Control Panel of Your Account. All notices to Pay10 shall be given electronically by sending an email to Pay10's email address listed within the Merchant Control Panel of Your Account.</p>
<h6><strong>19.3 Relationship of the Parties</strong></h6>
<p>The Parties are independent contractors, and nothing in this Agreement shall make them joint venturers, partners, employees, agents or other representatives of the other Party. Neither Party shall make any representation that suggests otherwise.</p>
<h6><strong>19.4 Assignment</strong></h6>
<p>You will not have the right or the power to assign any of Your rights or delegate the performance of any of Your obligations under this Agreement without the prior written consent of Pay10, including in the case of a merger. Pay10 will have the right, without prior written notice to You, to assign this Agreement to its successors and/or assigns, subsidiaries, affiliates, and/or Third-Party Service Providers.</p>
<h6><strong>19.5 Waiver</strong></h6>
<p>The failure of any Party to insist on or enforce strict performance of any provision of this Agreement or to exercise any right or remedy under this Agreement or applicable law will not be construed as a waiver or relinquishment to any extent of the right to assert or rely upon any such provision, right or remedy in that or any other instance; rather, the same will be and remain in full force and effect. Waiver by either Party of a breach of any provision contained in this Agreement must be in writing, and no such waiver will be construed as a waiver of any other and/or succeeding breach of such provision or a waiver of the provision itself.</p>
<h6><strong>19.6 Severability and Headings</strong></h6>
<p>If any provision of this Agreement is held to be invalid or unenforceable for any reason, the remaining provisions will continue in full force without being impaired or invalidated in any way. The Parties agree to replace any invalid provision with a valid provision which most closely approximates the intent and economic effect of the invalid provision. Headings are used for convenience of reference only and in no way define, limit, construe or describe the scope or extent of any section, or in any way affect this Agreement.</p>
<h6><strong>19.7 Force Majeure</strong></h6>
<p>Neither Party will be liable for any losses arising out of the delay or interruption of its performance of obligations under the Agreement due to any acts of God, acts of civil or military authorities, civil disturbances, disease, strife, wars, strikes or other labour disputes, fires, transportation contingencies, interruptions in telecommunications, utility, internet services or network provider services, or other catastrophes or any other occurrences which are beyond such Party's reasonable control (each a "Force Majeure Event"), provided that the delayed Party will provide the other Party notice of any such delay or interruption as soon as reasonably practicable, will use commercially reasonable efforts to minimize any delays or interruptions resulting from the Force Majeure Event, and in no event will any failure to pay any monetary sum due under this Agreement be excused for any Force Majeure Event.</p>
<h6><strong>19.8 Governing Law and Jurisdiction</strong></h6>
<p>19.8.1 This Agreement and all matters arising from or relating to it, including its validity, construction, performance, and enforcement, shall be governed by and construed in accordance with the laws of the Kingdom of Bahrain, without regard to any conflict of law principles.</p>
<p>19.8.2 The Parties shall endeavor in good faith to resolve any claim or dispute arising out of or in connection with this Agreement, including any question regarding its existence, validity, or termination, through amicable negotiations. If the dispute is not settled within thirty (30) days from the commencement of such negotiations (or such longer period as the Parties may agree in writing), the dispute shall be referred to and finally resolved by arbitration in accordance with the Bahrain Chamber for Dispute Resolution (BCDR-AAA) Arbitration Rules, which are deemed to be incorporated by reference into this clause. The seat (legal place) of arbitration shall be the Kingdom of Bahrain, and the language of arbitration shall be English. The arbitral tribunal shall consist of one (1) arbitrator, to be appointed in accordance with the BCDR-AAA Rules. The decision of the arbitrator shall be final and binding upon the Parties.</p>
<h6><strong>19.9 Entire Agreement</strong></h6>
<p>These Terms and Conditions, along with the Pay10 policies annexed to these Terms and Conditions and the Merchant Enrollment Form, set forth the entire understanding and agreement of the Parties and supersede all prior or contemporaneous oral or written agreements or understandings between the Parties as to the subject matter covered by these Terms and Conditions. You acknowledge that this Agreement reflects an informed and voluntary engagement between Pay10 and You of all risks (both known and unknown) associated with Pay10 Services.</p>
<h6><strong>19.10 Survival</strong></h6>
<p>The provisions of this Agreement relating to any fees or other amounts owed, payment of finance charge on unpaid fees, confidentiality, warranties, limitation of liability, indemnification, governing law, severability, headings, Third-Party beneficiary, this Section 19, and any other provisions that by their nature should survive termination shall survive termination or expiration of this Agreement.</p>

<h6><strong>Annexure A – Prohibited Activities</strong></h6>
<p>You agree that You will not at any time conduct Your business in any manner that directly or indirectly offers, sells, leases, licenses or displays, delivers, advertises, recommends, or promotes any product(s), service(s), data, information, image(s), text and/or any content which:</p>
<ul>
<li>(i) is unlawful or violates any applicable local, state, federal, national or international law, statute, ordinance, or regulation including, without limitation, Card Association rules, consumer protection laws, unfair competition, antidiscrimination or false advertising;</li>
<li>(ii) is associated with any illegal form of adult, sexually oriented, or obscene materials or services, including without limitation any material clearly designed to sexually arouse the viewer/reader with images of children less than 18 years old and/or escort services;</li>
<li>(iii) infringes on any patent, trademark, trade secret, copyright, right of publicity, or other proprietary right of any party, including, but not limited to, the unauthorized copying and posting of trademarks, pictures, logos, software, articles, musical works and videos;</li>
<li>(iv) is threatening, abusive, harassing, defamatory, obscene, libelous, slanderous, deceptive, fraudulent, invasive of another's privacy, tortious, or otherwise violates Pay10's rules or policies;</li>
<li>(v) victimizes, harasses, degrades, or intimidates an individual or group of individuals on the basis of religion, gender, sexual orientation, race, ethnicity, age, or disability;</li>
<li>(vi) impersonates any person or entity;</li>
<li>(vii) contains harmful content, including, without limitation, software viruses, Trojan horses, worms, time bombs, cancel bots, spyware, or any other files, software programs, or technology designed or intended to disrupt, damage, surreptitiously intercept or expropriate the Pay10 Services or any system, program, data or personal information, or limit the functioning of any software, hardware, or equipment, or to damage or obtain unauthorized access to any data or other information of any Third-Party;</li>
<li>(viii) violates any applicable export or import laws;</li>
<li>(ix) offers or disseminates fraudulent goods, services, schemes, or promotions (i.e., make-money-fast schemes, chain letters, pyramid schemes) or engages in any unfair deceptive act or practice;</li>
<li>(x) is associated with any form of illegal gambling or illegal lottery-type services;</li>
<li>(xi) is associated with illegal telecommunications or illegal cable television equipment or illegal satellite equipment, or is associated with shell banks or shell entities operating as shell companies without physical presence;</li>
<li>(xii) is associated with designated or sanctioned individuals or entities under applicable local and international lists, including but not limited to UN Security Council Resolutions.</li>
</ul>

<h6><strong>Annexure B – Service Levels and Critical Incident Management</strong></h6>
<p>Pay10 shall maintain commercially reasonable availability and support standards for the Pay10 Services and, where applicable, Pay10 Devices. To ensure operational stability and responsiveness, the following Service Levels shall apply:</p>
<h6><strong>1. Incident Classification</strong></h6>
<p>Incidents will be classified by severity:</p>
<table>
<thead>
<tr><th>Priority</th><th>Definition</th><th>Example</th></tr>
</thead>
<tbody>
<tr><td>P1</td><td>Full service outage or complete payment failure affecting all users</td><td>Entire platform down, no transactions process</td></tr>
<tr><td>P2</td><td>Degraded functionality impacting major processes or multiple users</td><td>Delays in transaction confirmations</td></tr>
<tr><td>P3</td><td>Partial, non-critical issues impacting minor features or isolated cases</td><td>Pay10 Device sync issues at one store</td></tr>
<tr><td>P4</td><td>Informational, cosmetic, or low-impact queries</td><td>Label misalignments, UI fixes</td></tr>
</tbody>
</table>
<h6><strong>2. Service Level Commitments</strong></h6>
<table>
<thead>
<tr><th>Priority</th><th>Response Time</th><th>Resolution Target</th><th>Communication Cadence</th></tr>
</thead>
<tbody>
<tr><td>P1</td><td>30 minutes</td><td>2 hours</td><td>Every 30 minutes</td></tr>
<tr><td>P2</td><td>1 hour</td><td>4 hours</td><td>Hourly updates</td></tr>
<tr><td>P3</td><td>4 business hours</td><td>1 business day</td><td>Daily status if required</td></tr>
<tr><td>P4</td><td>1 business day</td><td>3–5 business days</td><td>As agreed</td></tr>
</tbody>
</table>
<p>Note: These timelines apply during Working Days and Business Hours unless otherwise agreed.</p>
<h6><strong>3. Escalation and Oversight</strong></h6>
<p>In P1 or high-impact P2 scenarios, issues will be escalated to Pay10's senior technical and account management teams. Both Pay10 and the Merchant agree to designate named SPOCs (Single Points of Contact) to coordinate resolution and ensure rapid decision-making.</p>
<table>
<thead>
<tr><th>Level</th><th>Contact</th><th>Details</th></tr>
</thead>
<tbody>
<tr><td>Operations Center</td><td>Call center</td><td>Toll Free: 8001 1010, Email: <a href="mailto:merchantsupport@pay10.bh">merchantsupport@pay10.bh</a></td></tr>
<tr><td>Level 1</td><td>Ops Center Supervisor</td><td>Mobile: 1734341010, Email: <a href="mailto:L1merchantsupport@pay10.bh">L1merchantsupport@pay10.bh</a></td></tr>
<tr><td>Level 2</td><td>Senior Operations Manager</td><td>Mobile: 1734341010, Email: <a href="mailto:L2merchantsupport@pay10.bh">L2merchantsupport@pay10.bh</a></td></tr>
</tbody>
</table>
<h6><strong>4. Monitoring and Reporting</strong></h6>
<p>Pay10 will maintain tracking logs of reported issues and provide incident reports for P1/P2 cases upon resolution. These may include root cause analysis and remediation steps if required by the Merchant or regulator.</p>

<p><em>PAYTEN B.S.C. Closed | Commercial Registration No. 176109 – 1. Licensed by the Central Bank of Bahrain as an Ancillary Service Provider. www.pay10.bh | Office No 2202, Building No 1398, Road No 4626, Block No 346, Manama, Kingdom of Bahrain.</em></p>
`
  },
];

export default merchantTcsData;
